export const jobCategories = [
  'Delivery',
  'Cleaning',
  'IT',
  'Construction',
  'Labor',
  'Trade',
  'Gardening',
  'Moving',
  'Handyman',
  'Tutoring',
  'Healthcare',
  'Customer Service',
  'Design',
  'Marketing',
  'Administration',
  'Event Support',
  'Security',
  'Food Service',
  'Freelance',
  'Other',
];
